### ISSUE TITLE
The freezing problem of SHE and CHM modulation remains unsolved

### ISSUE THREAD

**Issue by MOPR290** [JOTAN-0655/VVVF-Simulator#8]
The SHE and CHM modulation still triggers freezing while the amplitude is outside the limit,thus we can not do any settings and have to restart the program.

**Comment by JOTAN-0655** [comment]
I have already done a brief solution for SHE and CHM modulation array index error.
So, I suppose there won't be any crash or freezing unless you're running on a specific condition.
Also, `Auto Voltage Set` is just a support tool so that it is not perfect yet. It might be improved in future updates.
Currently what can I say is wait till its `Auto Voltage Set` finish, or set manually.
Thank you.
